name: New Method Catalogue Entry
description: Request to add a new method to the catalogue
title: "[METHOD]: "
labels: ["method"]
assignees: jmillanacosta

body:
  - type: markdown
    attributes: 
      value: |
        Please fill out the form as completely as possible. Empty fields can be filled out later.
  - type: input
    id: name # ToxTemp 1.1
    attributes:
      label: Assay name
      description: The method can be a model, an assay, etc.
  - type: input
    id: data producer # ToxTemp ?
    attributes:
      label: Data producer
      description: Who generated the data?
  - type: input
    id: description # ToxTemp 1.2
    attributes:
      label: Method description
      description: A brief description of the method
  - type: input
    id: iri
    attributes:
      label: Type
      description: Glossary, ontology, or controlled vocabulary term IRI. Look up your term in the [Ontology Lookup Service](https://www.ebi.ac.uk/ols4/) or [Glossary](https://glossary.vhp4safety.nl/).
  - type: dropdown
    id: casestudy
    attributes:
      label: Relevant VHP4Safety regulatory question(s)
      description: Multiple selections possible. See the regulatory questions at this [link](https://docs.vhp4safety.nl/en/latest/introduction/case_studies_and_regulatory_questions.html).
      multiple: true
      options:
        - Kidney Disease (a)
        - Kidney Disease (b)
        - Life Course Pesticide Exposure and Neurodegenerative Disease (a)
        - Life Course Pesticide Exposure and Neurodegenerative Disease (b)
        - Thyroid Mediated Developmental Neurotoxicity (a)
        - Thyroid Mediated Developmental Neurotoxicity (b)
  - type: markdown
    attributes: 
      value: |
        ## Specification
  - type: input
    id: vendor # If cell: ToxTemp 3.1 // If method, no ToxTemp equivalent yet
    attributes:
      label: Vendor
      description: Vendor or provider of the method
  - type: input
    id: catalog_number # If cell: ToxTemp 3.1 // If method, no ToxTemp equivalent yet
    attributes:
      label: Catalog number
      description: Catalog entry for the method
      placeholder: e.g., R001
  - type: input
    id: catalog # If cell: ToxTemp 3.1 // If method, no ToxTemp equivalent yet
    attributes:
      label: Catalog webpage
  - type: input
    id: citation # ToxTemp 3.7
    attributes:
      label: Citation
      description: DOI or URL to a publication or SOP describing the method
  - type: dropdown
    id: stage
    attributes:
      label: VHP4Safety workflow stage
      multiple: true
      options:
       - Cheminformatics
       - External Exposure
       - Kinetics
       - AOP
       - Adverse Outcome
  - type: input
    id: substage
    attributes:
      label: Workflow substage
      placeholder: e.g. Exposure–response relationship
