name: New Method Catalogue Entry
description: Request to add a new method to the catalogue
title: "[METHOD]: "
labels: ["method"]

body:
  - type: markdown
    attributes: 
      value: |
        Please fill out the form as completely as possible. Empty fields can be filled out later.
  - type: input
    id: name
    attributes:
      label: Name of the method
      description: The method can be a model, an assay, etc.
  - type: input
    id: description
    attributes:
      label: Method description
      description: A brief description of the method
  - type: input
    id: iri
    attributes:
      label: Type
      description: Glossary, ontology, or controlled vocabulary term IRI. Look up your term in the [Ontology Lookup Service](https://www.ebi.ac.uk/ols4/) or [Glossary](https://glossary.vhp4safety.nl/).
  - type: dropdown
    id: casestudy
    attributes:
      label: Relevant VHP4Safety regulatory question(s)
      description: Multiple selections possible. See the regulatory questions at this [link](https://docs.vhp4safety.nl/en/latest/introduction/case_studies_and_regulatory_questions.html).
      multiple: true
      options:
        - Kidney Disease (a)
        - Kidney Disease (b)
        - Life Course Pesticide Exposure and Neurodegenerative Disease (a)
        - Life Course Pesticide Exposure and Neurodegenerative Disease (b)
        - Thyroid Mediated Developmental Neurotoxicity (a)
        - Thyroid Mediated Developmental Neurotoxicity (b)
  - type: markdown
    attributes: 
      value: |
        ## Specification
  - type: input
    id: provider
    attributes:
      label: Catalog entry
      description: Who is providing the method?
  - type: input
    id: catalog
    attributes:
      label: Catalog entry webpage
  - type: input
    id: citation
    attributes:
      label: Citation
      description: DOI or URL to a publication describing the method
  - type: dropdown
    id: stage
    attributes:
      label: VHP4Safety workflow stage
      multiple: true
      options:
       - Cheminformatics
       - External Exposure
       - Kinetics
       - AOP
       - Adverse Outcome
  - type: input
    id: substage
    attributes:
      label: Workflow substage
      placeholder: e.g. Exposure–response relationship
