name: Create Markdown

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/service/*.json'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/service/*.json'

jobs:
  webpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install groovy

      - name: Generate sitemap.xml
        run: groovy createSitemap.groovy > docs/sitemap.xml

      - name: Generate catalog
        run: cd docs ; groovy createCatalog.groovy > catalog.md ; groovy createIndex.groovy > index.md

      - name: Generate persona pages
        run: cd docs; groovy createPersona1.groovy > persona1.md ; groovy createPersona2.groovy > persona2.md ; groovy createPersona3.groovy > persona3.md

      - name: Generate service pages
        run: cd docs/service ; groovy createMarkdown.groovy *.json

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/sitemap.xml
          git add docs/index.md
          git add docs/catalog.md
          git add docs/persona1.md
          git add docs/persona2.md
          git add docs/persona3.md
          git add docs/service/*.md
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Updated service Markdown '
              git push
          fi
