name: Collect Service Meta-Data for CAP

on:
  push:
    paths:
      - 'docs/service/*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate combined JSON file
        run: python misc/generate_service_index.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/service/service_index.json
          git diff --cached --quiet || git commit -m "Auto-update service_index.json"
          git push
